apiVersion: v1 
kind: Pod  
metadata:
  name: pod-resources
  labels:
    name: pod-resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64mi"
        cpu: "250m"
      limits:
        memory: "100mi"
        cpu: "500m"