apiVersion: v1
kind:  Pod
metadata:
  name: multi-container
  labels:
    name: multicont 
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    command: ["sleep", "3600"] 
  
