apiVersion: v1
kind: Pod 
metadata:
  name: pod-config
  labels:
    name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: pod-config
          key: trainer
    - name: course 
      valueFrom:
        configMapKeyRef:
          name: pod-config
          key: course 