apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret
  labels:
    name: secretfile
  annotations: 
    username: "devops user from singapore"
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      secretRef:
      - name: my-secret



