apiVersion: v1
kind: pod
metadata: 
  name: pod-secret
  lables:
    name: secretfile
  annotations: 
    username: "devops user from singapore"
spec:
  containers:
  - name: nginx
    image: nginx
    secret:
      secretName: my-secret