apiVersion: v1
kind: Service
metadata: 
  name: nodeport
spec:
  type: NodePort 
  selector:
    project: expense
    module: backend
    environment: dev 
ports:
  - port: 80
    protocal: tcp
    tagetport: 80