apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    project: expense
    module: backend
    environment: dev 
  ports:
  - port: 80
    protocol: tcp
    tagetport: 80