apiVersion: v1 
kind: Pod 
metadata:
  name: podtesting
  namespace: expense 
  labels:
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  - name: almalinux
    image: almalinux
    command: ["sleep", "20000"]